spring:
  application:
    name: ou-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jueke/spring_cloud-leaning.git
          #uri: https://git.oschina.net/geek_qi/AG-Config.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8766


