spring:
  application:
    name: ou-gate
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  prefix: /api
  routes:
    uc:
      path: /uc/**
      serviceId: ou-uc
